repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
    - id: markdownlint-cli2
      args: ["--config", ".markdownlint.yaml"]

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        name: black-docs-text
        alias: black
        types_or: [markdown]
        additional_dependencies: [black==23.10.1]
        # Using PEP 8's line length in docs prevents excess left/right scrolling
        args: [--line-length=79]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black-jupyter
        name: black-docs-py
        alias: black
        files: ^(notebooks/)
        # Using PEP 8's line length in docs prevents excess left/right scrolling
        args: [--line-length=79]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    - id: codespell
      exclude: |
        static|
      args:
        [
          "--skip=*/algolia.js",
          "--ignore-words-list",
          "rouge",
        ]

  - repo: https://github.com/srstevenson/nb-clean
    rev: 4.0.1
    hooks:
      - id: nb-clean
        args: [--preserve-cell-outputs, --remove-empty-cells]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.9.6'
    hooks:
    - id: ruff
      args: [--fix, --extend-select, I, --exit-non-zero-on-fix, --config, ruff.toml]
      types_or: [python, jupyter]
    - id: ruff-format
      types_or: [python, jupyter]
